name: Build and Deploy
on:
  push:

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: rustup update
    - run: rustup target add wasm32v1-none

    - uses: stellar/stellar-cli@v22.8.1
    - run: stellar contract build --meta source_repo=github:${{ github.repository }}


    - name: Attestation
      uses: actions/attest-build-provenance@v1
      id: attestation
      with:
        subject-name: token-contract
        subject-path: target/wasm32v1-none/release/mycoin.wasm

    - name: Display Attestation Info
      run: |
        echo "Attestation created successfully!"
        echo "Check the Actions run summary for attestation details"

    - name: Upload to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mycoin.wasm
        path: target/wasm32v1-none/release/mycoin.wasm

    - name: Setup CLI for Testnet
      run: stellar network use testnet

    - name: Setup CLI with Deployer
      run: |
        stellar keys generate deployer --fund
        stellar keys use deployer


    - name: Install Contract with WASM Hash to TestNet (Verifiable)
      run: |
        WASM_HASH=$(stellar contract install --wasm target/wasm32v1-none/release/mycoin.wasm)
        echo "Contract installed with WASM hash: $WASM_HASH"
